parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    _instanceof:
        App\Blog\Application\CommandHandlerInterface:
            tags: ['app.command_handler']

        App\Blog\Application\QueryHandlerInterface:
            tags: ['app.query_handler']

        App\Blog\Infrastructure\Shared\ProjectionRepository\MysqlRepository:
            public: true

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Blog\Infrastructure\Shared\ServiceBus\QueryBus:
        public: true

    App\Blog\Infrastructure\Shared\ServiceBus\CommandBus:
        public: true

    App\Blog\System:
        public: true

    App\Blog\Infrastructure\Category\Repository\Projection\CategoryRepository:
        public: true

    App\Blog\Infrastructure\Category\Repository\Projection\MysqlCategoryProjection:
        public: true

    App\Symfony\Controller\:
        resource: '../src/Symfony/Controller'
        tags: ['controller.service_arguments']



