# Use root/example as user/password credentials
version: '3.1'

services:
  nginx:
    volumes:
      - ./:/var/www/project:delegated
      - ./docker/dev/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - db

  php:
    build: docker/dev/php
    volumes:
      - ./:/var/www/project:delegated
    links:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - 3308:3306
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: