# Use root/example as user/password credentials
version: '3.1'

services:
  nginx:
    image: nginx:1.17.3-alpine
    container_name: cqrs-blog-nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/project:cached
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - db
      - php

  php:
    build: ./docker/php
    container_name: cqrs-blog-php
    working_dir: /var/www/project
    volumes:
      - vendor:/var/www/project/vendor
      - var:/var/www/project/var
      - ./:/var/www/project:cached
    links:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - 3308:3306
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:5.0.5-alpine
    ports:
      - 6379:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

volumes:
  vendor:
  var:
  db_data: