# Use root/example as user/password credentials
version: '3.1'

services:
  nginx:
    image: nginx:1.17.3-alpine
    container_name: cqrs-blog-nginx
    ports:
      - "8080:80"
    links:
      - php

  php:
    container_name: cqrs-blog-php
    working_dir: /var/www/project

  redis:
    image: redis:5.0.5-alpine
    ports:
      - 6379:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
