version: 2
jobs:
  checkout-code:
    working_directory: ~/zawiszaty/cqrs-blog
    docker:
      - image: docker:18.09.3-git
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths: ./

  composer:
    working_directory: ~/zawiszaty/cqrs-blog
    docker:
      - image: zawiszaty/php:7.3
        user: zawiszaty
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS
    steps:
      - attach_workspace:
          at: ./
      - run: php composer.phar install
      - persist_to_workspace:
          root: .
          paths: ./vendor

  #
  # Build images:
  #
  build-php-image:
    working_directory: ~/zawiszaty/cqrs-blog
    docker:
      - image: docker:18.09.3-git
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.09.3
          docker_layer_caching: true
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker build --rm=false -f ci/circle/php/Dockerfile -t "${CIRCLE_PROJECT_REPONAME}-php" ./docker/php
      - run: docker tag "${CIRCLE_PROJECT_REPONAME}-backend" zawiszaty/circleci:cqrs-blog-${CIRCLE_SHA1}
      - run: docker push zawiszaty/circleci:cqrs-blog-${CIRCLE_SHA1}

  build-nginx-image:
    working_directory: ~/zawiszaty/cqrs-blog
    docker:
      - image: docker:18.09.3-git
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.09.3
          docker_layer_caching: true
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker build --rm=false -f ci/circle/php/Dockerfile -t "${CIRCLE_PROJECT_REPONAME}-nginx" ./docker/nginx
      - run: docker tag "${CIRCLE_PROJECT_REPONAME}-nginx" zawiszaty/circleci:cqrs-blog-${CIRCLE_SHA1}
      - run: docker push zawiszaty/circleci:cqrs-blog-${CIRCLE_SHA1}

  tests:
    docker:
      - image: zawiszaty/circleci:cqrs-blog-${CIRCLE_SHA1}
        user: zawiszaty
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS
        environment:
          #redis
          REDIS_HOSTNAME: redis
          REDIS_PORT: 6379
          #db
          DB_HOSTNAME: db
          DB_USERNAME: root
          DB_PORT: 3306
          DB_PASSWORD: 'admin'
      - image: mysql:5.7
        name: db
        environment:
          MYSQL_ROOT_PASSWORD: admin
      - image: redis:5-alpine
        name: redis
    working_directory: /var/www/html
    steps:
      - attach_workspace:
          at: ./
      # Wait for services:
      - run:
          name: Wait for Redis
          command: dockerize -wait tcp://$REDIS_HOSTNAME:$REDIS_PORT -timeout 30s
      - run:
          name: Wait for MySQL
          command: dockerize -wait tcp://$DB_HOSTNAME:$DB_PORT -timeout 30s

      # db up:
      - run: php bin/console d:d:c
      - run: php bin/console d:s:c

      # Run tests:
      - run: make test

workflows:
  version: 2
  build_and_test:
    jobs:
      - checkout-code:
      - build-php-image:
          requires:
            - checkout-code
      - backend-tests:
          requires:
            - build-php-image
            - composer