version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: make start
  test:
    machine: true
    steps:
      - run:
          name: run test
          command: 'make test'
      - run: make test