services:
    App\Blog\Infrastructure\Shared\Processor\ProjectionProcessorInterface: '@App\Blog\Infrastructure\Shared\Processor\SyncProjectionProcessor'
#    App\Blog\Infrastructure\Shared\Processor\ProjectionProcessorInterface: '@App\Blog\Infrastructure\Shared\Processor\AsyncProjectionProcessor'