services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $rabbitmqHost: '%env(RABBITMQ_HOST)%'
            $rabbitmgPort: '%env(RABBITMQ_PORT)%'
            $rabbitmqUser: '%env(RABBITMQ_USER)%'
            $rabbitmqPassword: '%env(RABBITMQ_PASSWORD)%'

    _instanceof:
        App\Blog\Application\CommandHandlerInterface:
            tags: ['app.command_handler']

        App\Blog\Application\QueryHandlerInterface:
            tags: ['app.query_handler']

        App\Blog\Infrastructure\Shared\ProjectionRepository\MysqlRepository:
            public: true

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Symfony/DTO,Tests,Kernel.php}'

    App\Blog\Infrastructure\Shared\ServiceBus\QueryBus:
        public: true

    App\Blog\Infrastructure\Shared\ServiceBus\CommandBus:
        public: true

    App\Blog\System:
        public: true

    App\Blog\Infrastructure\Category\Repository\Projection\CategoryRepository:
        public: true

    App\Blog\Infrastructure\User\Repository\Projection\UserRepository:
        public: true

    App\Blog\Infrastructure\User\Repository\Projection\MysqlUserProjection:
        public: true

    App\Blog\Infrastructure\Category\Repository\Projection\MysqlCategoryProjection:
        public: true

    App\Blog\Infrastructure\Category\Repository\Store\CategoryStoreRepository:
        public: true

    App\Blog\Infrastructure\Post\Repository\Projection\MysqlPostProjection:
        public: true

    App\Symfony\Controller\:
        resource: '../src/Symfony/Controller'
        tags: ['controller.service_arguments']

    doctrine.cache.redis:
        class: '%snc_redis.doctrine_cache_predis.class%'
        arguments:
            - '@snc_redis.default'
